name: Continuous Integration
on:
  push:
    branches:
      - main
      - pre-*

jobs:
  build:
    name: export pdf And bump version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Generate PDF from presentation
        run: |
          make export-pdf
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 22.0.12
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/github
            @semantic-release/exec
            @semantic-release/git
        env:
          GH_TOKEN: ${{ secrets.CI_TOKEN }}
      - name: store output next version
        id: next_version
        run: |
          echo "NEXT_VERSION=`git describe --tags --abbrev=0`" >> $GITHUB_OUTPUT
      - name: read next version
        run: |
          echo ${{ steps.next_version.outputs.NEXT_VERSION }}
